name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install
        run: yarn install

  frontend_build:
    name: "Frontend: Build"
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn install
        
      - name: Build
        run: yarn build
  
  frontend_deploy:
    name: "Frontend: Deploy"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: frontend_build
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: spaceboy0621docker  
          password: athena123123
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - run: >
          git_hash=`git rev-parse --short ${GITHUB_SHA}`
          current_date=`date +'%Y%m%d'`
          echo "::set-output name=docker_tag::${current_date}_github_${{ env.GITHUB_REF_SLUG }}_${git_hash}_${GITHUB_RUN_NUMBER}"
        id: docker_tag
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: spaceboy0621/reactapp
          push: true
